import Foundation

// MARK: - Bibliothèque d'exercices collège/lycée
struct CollegeContentLibrary {

    // Retourne : slides de cours (ordre fixe) + exercices mélangés
    static func exercises(for subject: CollegeSubject,
                          level: CollegeLevel,
                          language: CollegeLanguage = .french,
                          count: Int = 10) -> [CollegeExercise] {
        let lessons = lessonSlides(subject: subject, level: level, language: language)
        let pool    = allExercises(subject: subject, level: level, language: language)
        let evalCount = min(count - lessons.count, pool.count)
        return lessons + Array(pool.shuffled().prefix(max(0, evalCount)))
    }

    // MARK: - Slides de cours par matière
    private static func lessonSlides(subject: CollegeSubject, level: CollegeLevel, language: CollegeLanguage) -> [CollegeExercise] {
        guard language == .french else { return [] }
        switch subject {
        case .francais:      return francaisLessons(level: level)
        case .maths:         return mathsLessons(level: level)
        case .anglais:       return anglaisLessons(level: level)
        case .histoire:      return histoireLessons(level: level)
        case .sciences:      return sciencesLessons(level: level)
        case .communication: return communicationLessons(level: level)
        }
    }

    // MARK: - Cours Français
    private static func francaisLessons(level: CollegeLevel) -> [CollegeExercise] {
        if level.isLycee {
            return [
                .lesson(subject: .francais, emoji: "📜",
                        title: "Les figures de style",
                        body: "Une **métaphore** compare sans « comme » (ex: *il est un lion*). Une **comparaison** utilise « comme » ou « tel » (ex: *il est courageux comme un lion*). La **personnification** attribue des traits humains à un objet.",
                        narration: "Aujourd'hui on explore les figures de style, essentielles pour l'analyse littéraire au lycée."),
                .lesson(subject: .francais, emoji: "✍️",
                        title: "La dissertation",
                        body: "Une dissertation comporte **trois parties** : introduction (accroche + problématique + annonce du plan), **développement** (thèse, antithèse, synthèse), et **conclusion** (réponse à la problématique + ouverture).",
                        narration: "La dissertation est l'exercice phare du bac de français. Je t'explique la structure parfaite."),
            ]
        }
        return [
            .lesson(subject: .francais, emoji: "📝",
                    title: "Le nom et le groupe nominal",
                    body: "Un **nom** désigne une personne, un animal, une chose ou une idée. Il peut être **propre** (Paris, Marie) ou **commun** (chat, maison). Le **groupe nominal** est formé d'un déterminant + un nom (ex: *le chat*, *une belle maison*).",
                    narration: "Parlons grammaire ! Le nom est la brique de base de la phrase française."),
            .lesson(subject: .francais, emoji: "🔤",
                    title: "Les temps du passé",
                    body: "L'**imparfait** décrit une action habituelle ou un état (ex: *il jouait*). Le **passé composé** exprime une action terminée (ex: *il a joué*). Le **passé simple** s'utilise surtout à l'écrit pour des actions courtes (ex: *il joua*).",
                    narration: "Les temps du passé sont souvent confondus. Je vais t'aider à les distinguer facilement !"),
        ]
    }

    // MARK: - Cours Maths
    private static func mathsLessons(level: CollegeLevel) -> [CollegeExercise] {
        if level.isLycee {
            return [
                .lesson(subject: .maths, emoji: "📐",
                        title: "Les fonctions du second degré",
                        body: "Une fonction **trinôme** s'écrit f(x) = ax² + bx + c. Son **discriminant** est Δ = b² − 4ac. Si Δ > 0 : deux racines. Si Δ = 0 : une racine double. Si Δ < 0 : pas de racine réelle.",
                        narration: "Les fonctions du second degré sont au cœur du programme de seconde. Voici la méthode pas à pas."),
                .lesson(subject: .maths, emoji: "∫",
                        title: "Les dérivées",
                        body: "La **dérivée** d'une fonction mesure son taux de variation. Si f(x) = xⁿ alors **f'(x) = n·xⁿ⁻¹**. La dérivée d'une constante est **0**. La dérivée de sin(x) est **cos(x)**.",
                        narration: "La dérivation est une notion fondamentale en terminale. Apprenons les règles essentielles !"),
            ]
        }
        return [
            .lesson(subject: .maths, emoji: "🔢",
                    title: "Les fractions",
                    body: "Une **fraction** représente une division : **numérateur** ÷ **dénominateur**. Pour additionner des fractions, il faut le même dénominateur (dénominateur **commun**). Ex : 1/3 + 1/6 = 2/6 + 1/6 = **3/6 = 1/2**.",
                    narration: "Les fractions font peur à beaucoup d'élèves, mais avec la bonne méthode c'est simple !"),
            .lesson(subject: .maths, emoji: "📐",
                    title: "Le théorème de Pythagore",
                    body: "Dans un **triangle rectangle**, le carré de l'**hypoténuse** (le côté le plus long) est égal à la somme des carrés des deux autres côtés. **a² + b² = c²** où c est l'hypoténuse.",
                    narration: "Le théorème de Pythagore est l'un des théorèmes les plus célèbres des maths. Découvrons-le ensemble !"),
        ]
    }

    // MARK: - Cours Anglais
    private static func anglaisLessons(level: CollegeLevel) -> [CollegeExercise] { [
        .lesson(subject: .anglais, emoji: "🇬🇧",
                title: "Le prétérit simple",
                body: "Le **prétérit simple** exprime une action passée et terminée. Pour les verbes **réguliers**, on ajoute **-ed** (ex: *play → played*). Pour les verbes **irréguliers**, il faut les apprendre (ex: *go → went*, *see → saw*).",
                narration: "Today we learn the past simple tense in English! It's very useful to talk about what happened."),
        .lesson(subject: .anglais, emoji: "💬",
                title: "Les modaux",
                body: "Les **modaux** expriment des nuances : **can** = pouvoir/savoir, **must** = devoir (obligation), **should** = devoir (conseil), **may/might** = pouvoir (possibilité). Ils sont toujours suivis de l'**infinitif sans to**.",
                narration: "Modal verbs are essential in English! Let me explain how each one works."),
    ] }

    // MARK: - Cours Histoire-Géo
    private static func histoireLessons(level: CollegeLevel) -> [CollegeExercise] {
        if level.isLycee {
            return [
                .lesson(subject: .histoire, emoji: "🌍",
                        title: "La mondialisation",
                        body: "La **mondialisation** est l'intensification des échanges économiques, culturels et humains à l'échelle planétaire. Elle est portée par le **libre-échange**, les **multinationales** et les nouvelles technologies. Elle crée à la fois des richesses et des **inégalités**.",
                        narration: "La mondialisation est un sujet central en géographie au lycée. Analysons ses mécanismes."),
            ]
        }
        return [
            .lesson(subject: .histoire, emoji: "🏛️",
                    title: "La Révolution française",
                    body: "En **1789**, le peuple français se soulève contre le roi Louis XVI. Le **14 juillet 1789**, la Bastille est prise. La **Déclaration des droits de l'Homme** est rédigée. La devise **Liberté, Égalité, Fraternité** naît à cette époque.",
                    narration: "La Révolution française est un moment clé de notre histoire. Découvrons ensemble ce qui s'est passé !"),
            .lesson(subject: .histoire, emoji: "⚔️",
                    title: "La Première Guerre mondiale",
                    body: "La **Première Guerre mondiale** (1914-1918) oppose les **Alliés** (France, Royaume-Uni, Russie, puis États-Unis) aux **Empires centraux** (Allemagne, Autriche-Hongrie). C'est une guerre de **tranchées**. Elle cause plus de **18 millions** de morts.",
                    narration: "La Grande Guerre a bouleversé le monde entier. Voici les faits essentiels à connaître."),
        ]
    }

    // MARK: - Cours Sciences
    private static func sciencesLessons(level: CollegeLevel) -> [CollegeExercise] {
        if level.isLycee {
            return [
                .lesson(subject: .sciences, emoji: "⚛️",
                        title: "La structure de l'atome",
                        body: "L'**atome** est composé d'un **noyau** (protons + neutrons) entouré d'**électrons**. Le **numéro atomique Z** = nombre de protons. La **masse atomique A** = protons + neutrons. Un **ion** est un atome ayant gagné ou perdu des électrons.",
                        narration: "La chimie atomique est fondamentale pour comprendre la matière. Voici les bases indispensables !"),
            ]
        }
        return [
            .lesson(subject: .sciences, emoji: "🔬",
                    title: "La cellule vivante",
                    body: "Tous les **êtres vivants** sont composés de **cellules**. La cellule contient un **noyau** (avec l'ADN), une **membrane** (qui l'entoure) et du **cytoplasme**. Les cellules végétales ont en plus une **paroi** et des **chloroplastes**.",
                    narration: "La cellule est l'unité fondamentale du vivant. Découvrons sa structure fascinante !"),
            .lesson(subject: .sciences, emoji: "🌡️",
                    title: "Les états de la matière",
                    body: "La matière existe en **trois états** : **solide** (forme fixe), **liquide** (forme variable, volume fixe), **gazeux** (forme et volume variables). Le passage entre ces états s'appelle un **changement d'état** : fusion, solidification, vaporisation, condensation.",
                    narration: "L'eau peut être glace, liquide ou vapeur. Apprenons pourquoi et comment !"),
        ]
    }

    // MARK: - Cours Communication
    private static func communicationLessons(level: CollegeLevel) -> [CollegeExercise] { [
        .lesson(subject: .communication, emoji: "🗣️",
                title: "Exprimer ses émotions",
                body: "Reconnaître et exprimer ses **émotions** est important. Les émotions de base sont : **joie**, **tristesse**, **colère**, **peur**, **dégoût** et **surprise**. Dire « **Je me sens** ... » est plus précis que « ça va » ou « ça va pas ».",
                narration: "Parler de ce qu'on ressent, c'est une compétence qui s'apprend. Voyons comment bien exprimer ses émotions."),
        .lesson(subject: .communication, emoji: "🤝",
                title: "La communication non-violente",
                body: "La **Communication Non-Violente** (CNV) suit 4 étapes : **Observer** (les faits sans jugement), **Ressentir** (nommer l'émotion), **Besoin** (identifier ce qu'on souhaite), **Demander** (une action concrète et réalisable).",
                narration: "La communication non-violente permet de mieux se comprendre et éviter les conflits. C'est très utile au quotidien !"),
    ] }

    private static func allExercises(subject: CollegeSubject, level: CollegeLevel, language: CollegeLanguage) -> [CollegeExercise] {
        switch subject {
        case .francais:      return CollegeNativeLangLibrary.exercises(level: level, language: language)
        case .histoire:      return CollegeHistoryLibrary.exercises(level: level, language: language)
        case .maths:         return mathsExercises(level: level)
        case .anglais:       return anglaisExercises(level: level, language: language)
        case .sciences:      return sciencesExercises(level: level)
        case .communication: return communicationExercises(level: level)
        }
    }

    // MARK: - Langue étrangère
    private static func anglaisExercises(level: CollegeLevel, language: CollegeLanguage) -> [CollegeExercise] {
        if language == .english {
            return foreignFrenchForEnglish(level: level)
        }
        var pool: [CollegeExercise] = [
            ex(.anglais, .multipleChoice,
               "Translate: 'My name is...'",
               ["Je m'appelle / My name is", "J'ai / I have", "Je suis / I am", "J'aime / I like"], "Je m'appelle / My name is",
               "'My name is' in English = 'Je m'appelle' in French.", "🇬🇧", 1),
            ex(.anglais, .trueFalse,
               "In English: 'He go to school' is correct.",
               ["Vrai", "Faux"], "Faux",
               "With he/she/it, add -s: 'He goes to school'. Only 'I/you/we/they' use the base form.", "📚", 2),
            ex(.anglais, .fillBlank,
               "Complete: '___ is the capital of England.'",
               [], "London",
               "London is the capital of England, and one of the largest cities in Europe.", "🏙️", 1),
            ex(.anglais, .multipleChoice,
               "Past tense of 'to go':",
               ["went", "goed", "gone", "go"], "went",
               "'Go' is irregular: go → went → gone.", "⏰", 2),
            ex(.anglais, .oral,
               "Introduce yourself in 2 sentences in English.",
               [], "My name is... I am ... years old and I like...",
               "Self-introduction: name, age, interests. A key social and academic skill.", "🗣️", 1),
            ex(.anglais, .multipleChoice,
               "What does 'although' mean?",
               ["Even though / despite", "Because", "Therefore", "If"], "Even though / despite",
               "'Although' introduces a concession: 'Although it rains, we play.' = même si.", "💬", 3),
        ]
        if level.rawValue >= CollegeLevel.quatrieme.rawValue {
            pool += [
                ex(.anglais, .fillBlank,
                   "Complete (passive): 'The book ___ (to write) by J.K. Rowling.'",
                   [], "was written",
                   "Passive past: was/were + past participle. 'write' → 'written'.", "✍️", 3),
                ex(.anglais, .multipleChoice,
                   "What tense is: 'I will have finished by 5pm'?",
                   ["Future perfect", "Present continuous", "Conditional", "Past simple"], "Future perfect",
                   "'Will have + past participle' = future perfect. Action completed before a future point.", "⏳", 3),
            ]
        }
        return pool
    }

    private static func foreignFrenchForEnglish(level: CollegeLevel) -> [CollegeExercise] {
        var pool: [CollegeExercise] = [
            ex(.anglais, .multipleChoice,
               "How do you say 'My name is...' in French?",
               ["Je m'appelle...", "J'ai...", "Je suis...", "J'aime..."], "Je m'appelle...",
               "'Je m'appelle' literally means 'I call myself'. It's the standard French introduction.", "🇫🇷", 1),
            ex(.anglais, .trueFalse,
               "In French, adjectives usually come AFTER the noun.",
               ["True", "False"], "True",
               "E.g. 'une maison rouge' (a red house). Some short adjectives (grand, petit, beau) come before.", "📝", 2),
            ex(.anglais, .multipleChoice,
               "What does 'bonjour' mean?",
               ["Good morning / Hello", "Good night", "Goodbye", "Thank you"], "Good morning / Hello",
               "'Bonjour' is used as a daytime greeting in French. 'Bonsoir' is for the evening.", "👋", 1),
            ex(.anglais, .shortAnswer,
               "Conjugate 'avoir' (to have) for 'je'.",
               [], "j'ai",
               "'Avoir' is an irregular verb: j'ai, tu as, il a, nous avons, vous avez, ils ont.", "✍️", 2),
            ex(.anglais, .multipleChoice,
               "The French word for 'dog' is:",
               ["chien", "chat", "cheval", "cochon"], "chien",
               "Chien (m) = dog. Chat = cat. Cheval = horse. Cochon = pig.", "🐕", 1),
        ]
        if level.rawValue >= CollegeLevel.quatrieme.rawValue {
            pool += [
                ex(.anglais, .multipleChoice,
                   "Which is correct: 'Je suis allé' or 'J'ai allé'?",
                   ["Je suis allé", "J'ai allé", "Both are correct", "Neither"], "Je suis allé",
                   "'Aller' uses 'être' not 'avoir' in passé composé: je suis allé(e).", "⏰", 3),
                ex(.anglais, .shortAnswer,
                   "Translate: 'She has been living in Paris for three years.'",
                   [], "Elle habite à Paris depuis trois ans.",
                   "French uses present tense + 'depuis' where English uses present perfect continuous.", "🗼", 3),
            ]
        }
        return pool
    }

    // MARK: - Maths (70+ exercices, 6ème → Terminale)
    private static func mathsExercises(level: CollegeLevel) -> [CollegeExercise] {
        var pool: [CollegeExercise] = []

        // ── 6ème / 5ème : arithmétique, fractions, géométrie de base ──
        pool += [
            ex(.maths, .shortAnswer,
               "Calcule : 7 × 8 = ?",
               [], "56",
               "7 × 8 = 56. Les tables de multiplication sont la base du calcul.", "✖️", 1),
            ex(.maths, .multipleChoice,
               "Qu'est-ce qu'un nombre premier ?",
               ["Divisible seulement par 1 et lui-même", "Pair", "Multiple de 5", "Inférieur à 10"],
               "Divisible seulement par 1 et lui-même",
               "Un nombre premier n'a que deux diviseurs : 1 et lui-même. Ex : 2, 3, 5, 7, 11…", "🔢", 2),
            ex(.maths, .shortAnswer,
               "Calcule l'aire d'un rectangle de 5 cm × 3 cm.",
               [], "15 cm²",
               "Aire = longueur × largeur = 5 × 3 = 15 cm².", "📐", 1),
            ex(.maths, .trueFalse,
               "La somme des angles d'un triangle est toujours 180°.",
               ["Vrai", "Faux"], "Vrai",
               "La somme des angles intérieurs d'un triangle est toujours 180°.", "📐", 2),
            ex(.maths, .multipleChoice,
               "Quel est le résultat de 3² (trois au carré) ?",
               ["6", "9", "8", "12"], "9",
               "3² = 3 × 3 = 9. L'exposant 2 signifie qu'on multiplie le nombre par lui-même.", "🔢", 1),
            ex(.maths, .shortAnswer,
               "Simplifie la fraction 6/8.",
               [], "3/4",
               "On divise numérateur et dénominateur par leur PGCD (2) : 6÷2 = 3 et 8÷2 = 4.", "➗", 2),
            ex(.maths, .shortAnswer,
               "Calcule : 3/4 + 1/4 = ?",
               [], "1",
               "Pour additionner des fractions de même dénominateur, on additionne les numérateurs : 3+1=4, donc 4/4=1.", "➕", 1),
            ex(.maths, .multipleChoice,
               "Quel est le périmètre d'un carré de côté 6 cm ?",
               ["24 cm", "36 cm", "12 cm", "18 cm"], "24 cm",
               "Périmètre d'un carré = 4 × côté = 4 × 6 = 24 cm.", "📏", 1),
            ex(.maths, .shortAnswer,
               "Calcule : 1/2 + 1/3 = ?",
               [], "5/6",
               "On met au même dénominateur : 3/6 + 2/6 = 5/6.", "➕", 2),
            ex(.maths, .multipleChoice,
               "Quel est le pourcentage de 30 dans 120 ?",
               ["25 %", "30 %", "40 %", "20 %"], "25 %",
               "30 ÷ 120 × 100 = 25 %. On divise la partie par le tout et on multiplie par 100.", "📊", 2),
            ex(.maths, .shortAnswer,
               "Dans un triangle, deux angles mesurent 60° et 80°. Quel est le troisième ?",
               [], "40°",
               "180° − 60° − 80° = 40°. La somme des angles d'un triangle est 180°.", "📐", 1),
            ex(.maths, .multipleChoice,
               "Qu'est-ce qu'un nombre relatif ?",
               ["Un nombre positif ou négatif", "Un nombre pair", "Un nombre décimal", "Un nombre entier"],
               "Un nombre positif ou négatif",
               "Les nombres relatifs comprennent les entiers positifs, négatifs et zéro.", "±", 1),
            ex(.maths, .shortAnswer,
               "Calcule : (-3) + (+7) = ?",
               [], "4",
               "On soustrait la valeur absolue : 7 − 3 = 4. Le signe est celui du plus grand.", "➕", 1),
            ex(.maths, .shortAnswer,
               "Calcule : (-4) × (-5) = ?",
               [], "20",
               "Moins × moins = plus. (−4) × (−5) = +20.", "✖️", 2),
            ex(.maths, .multipleChoice,
               "Qu'est-ce que la proportionnalité ?",
               ["Un rapport constant entre deux grandeurs", "Une addition", "Un angle droit", "Un périmètre"],
               "Un rapport constant entre deux grandeurs",
               "Ex : si 3 stylos coûtent 6 €, le rapport est 2 €/stylo. C'est une situation de proportionnalité.", "📈", 2),
            ex(.maths, .shortAnswer,
               "Si 5 cahiers coûtent 10 €, combien coûtent 8 cahiers ?",
               [], "16 €",
               "Rapport : 10 ÷ 5 = 2 €/cahier. 8 × 2 = 16 €.", "💰", 1),
            ex(.maths, .multipleChoice,
               "L'aire d'un disque de rayon r est égale à :",
               ["π × r²", "2 × π × r", "π × r", "r²"], "π × r²",
               "Aire d'un disque = π × r². (Le périmètre/circonférence est 2πr.)", "⭕", 2),
            ex(.maths, .shortAnswer,
               "Calcule l'aire d'un triangle de base 8 cm et de hauteur 5 cm.",
               [], "20 cm²",
               "Aire = (base × hauteur) ÷ 2 = (8 × 5) ÷ 2 = 20 cm².", "📐", 1),
            ex(.maths, .trueFalse,
               "0 est un nombre relatif.",
               ["Vrai", "Faux"], "Vrai",
               "0 appartient à l'ensemble des entiers relatifs (ni positif ni négatif).", "0️⃣", 1),
            ex(.maths, .multipleChoice,
               "Parmi ces nombres, lequel est premier ?",
               ["13", "15", "21", "27"], "13",
               "13 n'est divisible que par 1 et 13. 15=3×5, 21=3×7, 27=3×9.", "🔢", 2),
            ex(.maths, .shortAnswer,
               "Quel est le PGCD de 12 et 18 ?",
               [], "6",
               "Les diviseurs de 12 : 1,2,3,4,6,12. Ceux de 18 : 1,2,3,6,9,18. Le plus grand commun est 6.", "🔢", 2),
            ex(.maths, .multipleChoice,
               "Convertis 3,5 km en mètres.",
               ["3 500 m", "350 m", "35 m", "35 000 m"], "3 500 m",
               "1 km = 1 000 m. Donc 3,5 km = 3 500 m.", "📏", 1),
            ex(.maths, .shortAnswer,
               "Calcule 20 % de 150.",
               [], "30",
               "20 % = 20/100. 150 × 20/100 = 30.", "📊", 1),

            // Statistiques de base
            ex(.maths, .shortAnswer,
               "Calcule la moyenne de : 10, 12, 14, 16.",
               [], "13",
               "Moyenne = somme ÷ nombre = (10+12+14+16) ÷ 4 = 52 ÷ 4 = 13.", "📊", 1),
            ex(.maths, .multipleChoice,
               "Dans une série de données, la médiane est :",
               ["La valeur centrale quand les données sont ordonnées", "La valeur la plus fréquente", "La moyenne", "La plus grande valeur"],
               "La valeur centrale quand les données sont ordonnées",
               "La médiane partage la série en deux moitiés égales une fois les valeurs ordonnées.", "📊", 2),
        ]

        // ── 4ème / 3ème : équations, Pythagore, trig, puissances, stats ──
        if level.rawValue >= CollegeLevel.quatrieme.rawValue {
            pool += [
                ex(.maths, .multipleChoice,
                   "Qu'est-ce qu'une équation ?",
                   ["Une égalité avec une inconnue", "Un calcul sans inconnue", "Une fraction", "Un triangle"],
                   "Une égalité avec une inconnue",
                   "Une équation est une égalité contenant une inconnue (souvent x) à trouver.", "❓", 2),
                ex(.maths, .shortAnswer,
                   "Résous : x + 5 = 12, x = ?",
                   [], "7",
                   "x = 12 − 5 = 7. On isole l'inconnue en faisant la même opération des deux côtés.", "🔡", 2),
                ex(.maths, .shortAnswer,
                   "Résous : 3x − 4 = 11, x = ?",
                   [], "5",
                   "3x = 11 + 4 = 15, donc x = 15 ÷ 3 = 5.", "🔡", 2),
                ex(.maths, .shortAnswer,
                   "Développe : (x + 3)(x + 2) = ?",
                   [], "x² + 5x + 6",
                   "(x+3)(x+2) = x²+2x+3x+6 = x²+5x+6. On utilise la distributivité double.", "📊", 3),
                ex(.maths, .shortAnswer,
                   "Factorise : x² − 9.",
                   [], "(x − 3)(x + 3)",
                   "x² − 9 = x² − 3² = (x−3)(x+3). C'est l'identité remarquable a²−b²=(a−b)(a+b).", "📊", 3),
                ex(.maths, .multipleChoice,
                   "Le théorème de Pythagore s'applique à :",
                   ["Un triangle rectangle", "Tout triangle", "Un carré", "Un cercle"],
                   "Un triangle rectangle",
                   "Pythagore : dans un triangle rectangle, a²+b²=c² où c est l'hypoténuse.", "📐", 3),
                ex(.maths, .shortAnswer,
                   "Dans un triangle rectangle, les deux cathètes mesurent 3 et 4. Quelle est l'hypoténuse ?",
                   [], "5",
                   "3² + 4² = 9 + 16 = 25, donc hypoténuse = √25 = 5. C'est le triplet pythagoricien 3-4-5.", "📐", 2),
                ex(.maths, .trueFalse,
                   "√16 = 4",
                   ["Vrai", "Faux"], "Vrai",
                   "√16 = 4 car 4² = 16. La racine carrée est l'opération inverse du carré.", "√", 2),
                ex(.maths, .shortAnswer,
                   "Calcule le périmètre d'un cercle de rayon 5 cm. (π ≈ 3,14)",
                   [], "31,4 cm",
                   "P = 2 × π × r = 2 × 3,14 × 5 = 31,4 cm.", "⭕", 3),
                ex(.maths, .multipleChoice,
                   "Dans un triangle rectangle, sin(angle) = ?",
                   ["côté opposé / hypoténuse", "côté adjacent / hypoténuse", "côté opposé / côté adjacent", "hypoténuse / côté opposé"],
                   "côté opposé / hypoténuse",
                   "SOH-CAH-TOA : Sin = Opposé/Hypoténuse, Cos = Adjacent/Hypoténuse, Tan = Opposé/Adjacent.", "📐", 3),
                ex(.maths, .shortAnswer,
                   "Dans un triangle rectangle, cos(30°) ≈ 0,87. Si l'hypoténuse vaut 10, quel est le côté adjacent ?",
                   [], "8,7",
                   "côté adjacent = cos(30°) × hypoténuse = 0,87 × 10 = 8,7.", "📐", 3),
                ex(.maths, .multipleChoice,
                   "Que vaut 2³ ?",
                   ["8", "6", "9", "4"], "8",
                   "2³ = 2 × 2 × 2 = 8. La puissance indique combien de fois on multiplie le nombre par lui-même.", "🔢", 2),
                ex(.maths, .shortAnswer,
                   "Simplifie : 10⁴ ÷ 10² = ?",
                   [], "10² = 100",
                   "Règle des puissances : aᵐ ÷ aⁿ = aᵐ⁻ⁿ. Donc 10⁴ ÷ 10² = 10² = 100.", "🔢", 2),
                ex(.maths, .multipleChoice,
                   "Résous le système : x + y = 5 et x − y = 1.",
                   ["x = 3, y = 2", "x = 2, y = 3", "x = 4, y = 1", "x = 1, y = 4"],
                   "x = 3, y = 2",
                   "En additionnant les deux équations : 2x = 6, x = 3. Puis y = 5 − 3 = 2.", "🔡", 3),
                ex(.maths, .shortAnswer,
                   "Calcule √49.",
                   [], "7",
                   "7² = 49, donc √49 = 7.", "√", 1),
                ex(.maths, .multipleChoice,
                   "La probabilité d'un événement certain est :",
                   ["1", "0", "0,5", "2"], "1",
                   "Une probabilité est comprise entre 0 (impossible) et 1 (certain).", "🎲", 2),
                ex(.maths, .shortAnswer,
                   "On lance un dé à 6 faces. Quelle est la probabilité d'obtenir un 4 ?",
                   [], "1/6",
                   "Il y a 1 résultat favorable sur 6 possibles : P(4) = 1/6.", "🎲", 2),
                ex(.maths, .multipleChoice,
                   "L'étendue d'une série statistique est :",
                   ["Valeur max − valeur min", "Somme des valeurs", "Moyenne", "Valeur la plus fréquente"],
                   "Valeur max − valeur min",
                   "L'étendue mesure la dispersion d'une série : étendue = max − min.", "📊", 2),
                ex(.maths, .shortAnswer,
                   "Calcule l'étendue de : 5, 12, 3, 8, 15.",
                   [], "12",
                   "Max = 15, min = 3. Étendue = 15 − 3 = 12.", "📊", 2),
            ]
        }

        // ── Lycée : fonctions, dérivées, vecteurs, suites, log, probabilités ──
        if level.isLycee {
            pool += [
                ex(.maths, .shortAnswer,
                   "Calcule la dérivée de f(x) = x³ + 2x.",
                   [], "f'(x) = 3x² + 2",
                   "La dérivée de xⁿ est n·xⁿ⁻¹. Donc (x³)' = 3x² et (2x)' = 2.", "📈", 3),
                ex(.maths, .multipleChoice,
                   "Qu'est-ce qu'un vecteur ?",
                   ["Un segment orienté", "Un angle", "Un cercle", "Une fraction"],
                   "Un segment orienté",
                   "Un vecteur est défini par une direction, un sens et une norme (longueur).", "➡️", 3),
                ex(.maths, .shortAnswer,
                   "Quelle est la dérivée de f(x) = x² − 3x + 1 ?",
                   [], "f'(x) = 2x − 3",
                   "(x²)' = 2x, (−3x)' = −3, (1)' = 0. Donc f'(x) = 2x − 3.", "📈", 3),
                ex(.maths, .multipleChoice,
                   "Une fonction affine a la forme :",
                   ["f(x) = ax + b", "f(x) = ax²", "f(x) = a/x", "f(x) = √x"],
                   "f(x) = ax + b",
                   "Une fonction affine est de la forme f(x) = ax + b. Son graphe est une droite.", "📈", 2),
                ex(.maths, .shortAnswer,
                   "Détermine le sommet de la parabole f(x) = (x − 2)² + 3.",
                   [], "(2, 3)",
                   "La forme f(x) = (x−h)² + k donne directement le sommet (h, k) = (2, 3).", "📈", 3),
                ex(.maths, .multipleChoice,
                   "log₁₀(100) = ?",
                   ["2", "10", "1", "100"], "2",
                   "log₁₀(100) = 2 car 10² = 100. Le logarithme décimal est l'exposant de 10.", "🔢", 3),
                ex(.maths, .shortAnswer,
                   "Que vaut ln(e) ?",
                   [], "1",
                   "ln(e) = 1 par définition, car e¹ = e. Le logarithme naturel est l'inverse de l'exponentielle.", "🔢", 3),
                ex(.maths, .multipleChoice,
                   "Une suite arithmétique est définie par :",
                   ["uₙ₊₁ = uₙ + r (raison constante)", "uₙ₊₁ = uₙ × q", "uₙ = n²", "uₙ = 1/n"],
                   "uₙ₊₁ = uₙ + r (raison constante)",
                   "Une suite arithmétique a une différence constante r entre deux termes consécutifs.", "🔢", 3),
                ex(.maths, .shortAnswer,
                   "Pour la suite arithmétique u₀ = 3 et r = 4, calcule u₅.",
                   [], "23",
                   "uₙ = u₀ + n × r. u₅ = 3 + 5 × 4 = 3 + 20 = 23.", "🔢", 3),
                ex(.maths, .multipleChoice,
                   "La dérivée d'une constante est :",
                   ["0", "1", "La constante elle-même", "Indéfinie"], "0",
                   "La dérivée d'une fonction constante f(x) = k est f'(x) = 0.", "📈", 2),
                ex(.maths, .shortAnswer,
                   "Calcule la dérivée de f(x) = sin(x).",
                   [], "f'(x) = cos(x)",
                   "La dérivée de sin(x) est cos(x). C'est une formule de base à mémoriser.", "📈", 3),
                ex(.maths, .multipleChoice,
                   "La probabilité conditionnelle P(A|B) représente :",
                   ["P(A sachant que B est réalisé)", "P(A et B)", "P(A ou B)", "P(A) × P(B)"],
                   "P(A sachant que B est réalisé)",
                   "P(A|B) = P(A∩B) / P(B). C'est la probabilité de A quand on sait que B est arrivé.", "🎲", 3),
                ex(.maths, .shortAnswer,
                   "Deux vecteurs u(1;2) et v(3;4). Calcule u + v.",
                   [], "(4 ; 6)",
                   "On additionne coordonnée par coordonnée : (1+3 ; 2+4) = (4 ; 6).", "➡️", 3),
                ex(.maths, .multipleChoice,
                   "Dans un repère orthonormé, la distance entre A(0;0) et B(3;4) est :",
                   ["5", "7", "4", "√7"], "5",
                   "d = √((3−0)²+(4−0)²) = √(9+16) = √25 = 5.", "📐", 3),
                ex(.maths, .trueFalse,
                   "La dérivée de eˣ est eˣ.",
                   ["Vrai", "Faux"], "Vrai",
                   "L'exponentielle est sa propre dérivée : (eˣ)' = eˣ. C'est une propriété remarquable.", "📈", 3),
                ex(.maths, .shortAnswer,
                   "Résous l'inéquation : 2x − 3 > 5.",
                   [], "x > 4",
                   "2x > 5 + 3 = 8, donc x > 4.", "🔡", 2),
                ex(.maths, .multipleChoice,
                   "La loi normale est aussi appelée :",
                   ["Courbe de Gauss / loi en cloche", "Loi uniforme", "Loi exponentielle", "Loi binomiale"],
                   "Courbe de Gauss / loi en cloche",
                   "La loi normale (Gauss) est symétrique autour de la moyenne et très utilisée en statistiques.", "🔔", 3),
                ex(.maths, .shortAnswer,
                   "Donne la formule du produit scalaire de deux vecteurs u(a;b) et v(c;d).",
                   [], "u·v = ac + bd",
                   "Le produit scalaire en coordonnées cartésiennes : u·v = ac + bd.", "➡️", 3),
                ex(.maths, .multipleChoice,
                   "Une fonction est croissante sur un intervalle si sa dérivée est :",
                   ["Positive ou nulle", "Négative", "Nulle", "Indéfinie"],
                   "Positive ou nulle",
                   "Si f'(x) ≥ 0 sur [a;b] alors f est croissante sur [a;b].", "📈", 3),
                ex(.maths, .shortAnswer,
                   "Calcule ∫₀² 2x dx.",
                   [], "4",
                   "∫2x dx = x². Évalué de 0 à 2 : 2² − 0² = 4. L'intégrale mesure l'aire sous la courbe.", "📈", 3),
                ex(.maths, .multipleChoice,
                   "Que signifie 'n!' (factorielle n) ?",
                   ["n × (n−1) × (n−2) × … × 1", "n × n", "n + (n−1) + …", "nⁿ"],
                   "n × (n−1) × (n−2) × … × 1",
                   "Ex : 4! = 4×3×2×1 = 24. Les factorielles servent au dénombrement et aux probabilités.", "🔢", 3),
                ex(.maths, .shortAnswer,
                   "Calcule le discriminant de x² − 5x + 6 = 0.",
                   [], "1",
                   "Δ = b² − 4ac = (−5)² − 4×1×6 = 25 − 24 = 1.", "📊", 3),
                ex(.maths, .multipleChoice,
                   "Deux solutions réelles existent si le discriminant est :",
                   ["Strictement positif (Δ > 0)", "Nul (Δ = 0)", "Négatif (Δ < 0)", "Quelconque"],
                   "Strictement positif (Δ > 0)",
                   "Δ > 0 → 2 solutions ; Δ = 0 → 1 solution (double) ; Δ < 0 → pas de solution réelle.", "📊", 3),
            ]
        }

        return pool
    }

    // MARK: - Sciences SVT + Physique-Chimie (70+ exercices)
    private static func sciencesExercises(level: CollegeLevel) -> [CollegeExercise] {
        var pool: [CollegeExercise] = []

        // ── 6ème / 5ème : cellule, écosystèmes, corps humain, matière, lumière ──
        pool += [
            ex(.sciences, .trueFalse,
               "La photosynthèse produit de l'oxygène.",
               ["Vrai", "Faux"], "Vrai",
               "Les plantes utilisent CO₂ + eau + lumière → glucose + O₂ (oxygène).", "🌿", 1),
            ex(.sciences, .multipleChoice,
               "Quelle est la formule chimique de l'eau ?",
               ["H₂O", "CO₂", "O₂", "NaCl"], "H₂O",
               "L'eau est composée de 2 atomes d'hydrogène et 1 atome d'oxygène.", "💧", 1),
            ex(.sciences, .shortAnswer,
               "Cite les 3 états de la matière.",
               [], "Solide, liquide, gazeux",
               "La matière peut être solide (glace), liquide (eau) ou gazeuse (vapeur).", "🧊", 1),
            ex(.sciences, .oral,
               "Explique le cycle de l'eau en 2 phrases.",
               [], "L'eau s'évapore, forme des nuages, puis retombe en pluie.",
               "Le cycle de l'eau : évaporation → condensation → précipitations → ruissellement → évaporation.", "☁️", 2),
            ex(.sciences, .multipleChoice,
               "Quel organe filtre le sang dans notre corps ?",
               ["Les reins", "Le cœur", "Les poumons", "Le foie"], "Les reins",
               "Les reins filtrent le sang et produisent l'urine pour éliminer les déchets.", "🫘", 1),
            ex(.sciences, .multipleChoice,
               "La cellule est l'unité de base du vivant. La membrane cellulaire sert à :",
               ["Délimiter la cellule et contrôler les échanges", "Produire de l'énergie", "Fabriquer des protéines", "Stocker l'ADN"],
               "Délimiter la cellule et contrôler les échanges",
               "La membrane cellulaire entoure la cellule et régule ce qui entre et ce qui sort.", "🔬", 1),
            ex(.sciences, .trueFalse,
               "Toutes les cellules d'un organisme ont le même ADN.",
               ["Vrai", "Faux"], "Vrai",
               "Chaque cellule d'un individu (sauf les gamètes) contient le même génome.", "🧬", 2),
            ex(.sciences, .shortAnswer,
               "Quel organite de la cellule végétale réalise la photosynthèse ?",
               [], "Le chloroplaste",
               "Les chloroplastes contiennent de la chlorophylle qui capte la lumière pour la photosynthèse.", "🌿", 2),
            ex(.sciences, .multipleChoice,
               "Un écosystème comprend :",
               ["Les êtres vivants et leur milieu", "Uniquement les animaux", "Uniquement les plantes", "Le sol seul"],
               "Les êtres vivants et leur milieu",
               "Un écosystème = biocénose (êtres vivants) + biotope (milieu physique).", "🌍", 1),
            ex(.sciences, .shortAnswer,
               "Donne deux exemples de producteurs dans une chaîne alimentaire.",
               [], "Herbe / algue / blé / arbres",
               "Les producteurs sont des végétaux qui fabriquent leur matière organique par photosynthèse.", "🌱", 1),
            ex(.sciences, .multipleChoice,
               "La digestion transforme les aliments en :",
               ["Nutriments absorbables par le sang", "Énergie directement", "CO₂ et eau", "Déchets uniquement"],
               "Nutriments absorbables par le sang",
               "La digestion mécanique et chimique décompose les aliments en molécules simples : glucose, acides aminés, acides gras.", "🍽️", 1),
            ex(.sciences, .trueFalse,
               "La lumière blanche est composée d'une seule couleur.",
               ["Vrai", "Faux"], "Faux",
               "La lumière blanche est composée de toutes les couleurs de l'arc-en-ciel (spectre visible).", "🌈", 1),
            ex(.sciences, .multipleChoice,
               "Quel est le rôle des poumons ?",
               ["Apporter O₂ au sang et éliminer CO₂", "Filtrer le sang", "Digérer les aliments", "Produire des hormones"],
               "Apporter O₂ au sang et éliminer CO₂",
               "Les poumons assurent les échanges gazeux : O₂ entre dans le sang, CO₂ en sort.", "🫁", 1),
            ex(.sciences, .shortAnswer,
               "Donne la formule de la photosynthèse (en mots).",
               [], "CO₂ + eau + lumière → glucose + O₂",
               "Les plantes fabriquent du glucose (sucre) à partir du dioxyde de carbone et de l'eau grâce à la lumière.", "🌿", 2),
            ex(.sciences, .multipleChoice,
               "La respiration cellulaire produit :",
               ["De l'énergie, CO₂ et eau", "Du glucose", "De l'oxygène", "Des protéines"],
               "De l'énergie, CO₂ et eau",
               "Glucose + O₂ → énergie (ATP) + CO₂ + H₂O. C'est l'inverse de la photosynthèse.", "⚡", 2),
            ex(.sciences, .shortAnswer,
               "Quel changement d'état se produit quand l'eau passe de liquide à solide ?",
               [], "La solidification (ou congélation)",
               "L'eau se solidifie à 0°C. L'opération inverse (solide → liquide) est la fusion.", "🧊", 1),
            ex(.sciences, .multipleChoice,
               "La biodiversité désigne :",
               ["La variété des êtres vivants sur Terre", "Le nombre d'espèces disparues", "L'air pur", "Le sol fertile"],
               "La variété des êtres vivants sur Terre",
               "La biodiversité inclut la diversité des espèces, des gènes et des écosystèmes.", "🌍", 1),
            ex(.sciences, .trueFalse,
               "Les champignons sont des plantes.",
               ["Vrai", "Faux"], "Faux",
               "Les champignons forment un règne distinct : ils n'ont pas de chlorophylle et ne font pas la photosynthèse.", "🍄", 2),
            ex(.sciences, .shortAnswer,
               "Qu'est-ce qu'un vertébré ? Donne deux exemples.",
               [], "Animal possédant une colonne vertébrale. Ex : poisson, oiseau, mammifère.",
               "Les vertébrés se distinguent des invertébrés par leur squelette interne avec une colonne vertébrale.", "🐟", 1),
            ex(.sciences, .multipleChoice,
               "La lune brille parce qu'elle :",
               ["Réfléchit la lumière du soleil", "Produit sa propre lumière", "Est en feu", "Capte la lumière des étoiles"],
               "Réfléchit la lumière du soleil",
               "La lune est un astre non lumineux (corps sombre) : elle ne fait que réfléchir la lumière solaire.", "🌕", 1),
            ex(.sciences, .shortAnswer,
               "Cite deux sources d'énergie renouvelable.",
               [], "Soleil (solaire) / vent (éolien) / eau (hydraulique) / géothermie",
               "Les énergies renouvelables sont inépuisables à l'échelle humaine, contrairement aux combustibles fossiles.", "☀️", 1),
        ]

        // ── 4ème / 3ème : atome, électricité, chimie, corps humain, mécanique ──
        if level.rawValue >= CollegeLevel.quatrieme.rawValue {
            pool += [
                ex(.sciences, .multipleChoice,
                   "De quoi est composé un atome ?",
                   ["Protons, neutrons, électrons", "Molécules et ions", "Cellules", "Photons"],
                   "Protons, neutrons, électrons",
                   "L'atome est formé d'un noyau (protons + neutrons) entouré d'électrons.", "⚛️", 2),
                ex(.sciences, .multipleChoice,
                   "Qu'est-ce que la mitose ?",
                   ["Division cellulaire", "Reproduction sexuée", "Photosynthèse", "Digestion"],
                   "Division cellulaire",
                   "La mitose est la division d'une cellule en deux cellules filles identiques.", "🔬", 3),
                ex(.sciences, .trueFalse,
                   "La vitesse de la lumière dans le vide est d'environ 300 000 km/s.",
                   ["Vrai", "Faux"], "Vrai",
                   "La vitesse de la lumière dans le vide est c ≈ 3×10⁸ m/s = 300 000 km/s.", "💡", 2),
                ex(.sciences, .shortAnswer,
                   "Quelle est la formule de la force (2ème loi de Newton) ?",
                   [], "F = m × a",
                   "F (force en Newtons) = m (masse en kg) × a (accélération en m/s²).", "⚖️", 3),
                ex(.sciences, .shortAnswer,
                   "Donne la formule de la loi d'Ohm.",
                   [], "U = R × I",
                   "Loi d'Ohm : U (tension en volts) = R (résistance en ohms) × I (intensité en ampères).", "⚡", 2),
                ex(.sciences, .multipleChoice,
                   "Dans un circuit en série, l'intensité du courant est :",
                   ["La même partout", "Différente selon les composants", "Nulle", "Doublée"],
                   "La même partout",
                   "Dans un circuit série, I est identique en tout point. La tension se répartit entre les composants.", "🔌", 2),
                ex(.sciences, .multipleChoice,
                   "Un atome est électriquement neutre car :",
                   ["Il a autant de protons que d'électrons", "Il n'a pas de neutrons", "Ses électrons sont dans le noyau", "Sa masse est nulle"],
                   "Il a autant de protons que d'électrons",
                   "Protons (+) et électrons (−) se compensent, l'atome est donc neutre.", "⚛️", 2),
                ex(.sciences, .shortAnswer,
                   "Quelle est la différence entre un acide et une base selon le pH ?",
                   [], "Acide : pH < 7 ; Base : pH > 7 ; Neutre : pH = 7",
                   "Le pH mesure la concentration en ions H⁺. Acide = beaucoup d'H⁺, base = peu d'H⁺.", "🧪", 2),
                ex(.sciences, .multipleChoice,
                   "La réaction de combustion du carbone produit :",
                   ["CO₂", "H₂O", "O₂", "NaCl"],
                   "CO₂",
                   "C + O₂ → CO₂. C'est pourquoi brûler des combustibles fossiles augmente le CO₂ atmosphérique.", "🔥", 2),
                ex(.sciences, .shortAnswer,
                   "Calcule la vitesse d'un objet qui parcourt 150 m en 5 s.",
                   [], "30 m/s",
                   "v = d/t = 150/5 = 30 m/s. La vitesse est le rapport distance/temps.", "🚀", 2),
                ex(.sciences, .multipleChoice,
                   "Le système nerveux central comprend :",
                   ["Le cerveau et la moelle épinière", "Les nerfs et les muscles", "Le cœur et les poumons", "Les yeux et les oreilles"],
                   "Le cerveau et la moelle épinière",
                   "Le SNC traite l'information. Le système nerveux périphérique relie le SNC aux organes.", "🧠", 2),
                ex(.sciences, .trueFalse,
                   "Les plaques tectoniques se déplacent d'environ 1 à 10 cm par an.",
                   ["Vrai", "Faux"], "Vrai",
                   "La tectonique des plaques est très lente mais ses effets (séismes, volcans) sont immenses.", "🌋", 2),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce qu'une réaction chimique ?",
                   [], "Une transformation où des réactifs se convertissent en produits avec formation de nouvelles liaisons.",
                   "Lors d'une réaction chimique, les atomes se réarrangent mais leur nombre total est conservé (conservation de la masse).", "🧪", 2),
                ex(.sciences, .multipleChoice,
                   "La pression artérielle est mesurée en :",
                   ["mmHg (millimètres de mercure)", "Newtons", "Pascals uniquement", "Ampères"],
                   "mmHg (millimètres de mercure)",
                   "La tension artérielle normale est d'environ 120/80 mmHg. Le premier chiffre est la systolique.", "💉", 3),
                ex(.sciences, .shortAnswer,
                   "Cite deux hormones et leur rôle.",
                   [], "Insuline : régule la glycémie / Adrénaline : prépare à l'effort / Testostérone : caractères sexuels",
                   "Les hormones sont des messagers chimiques produits par les glandes endocrines.", "🧬", 3),
                ex(.sciences, .multipleChoice,
                   "Qu'est-ce que la fécondation ?",
                   ["La fusion d'un spermatozoïde et d'un ovule", "Le développement du fœtus", "La naissance", "La puberté"],
                   "La fusion d'un spermatozoïde et d'un ovule",
                   "La fécondation forme un œuf (zygote) qui contient 46 chromosomes (23 de chaque parent).", "🔬", 2),
            ]
        }

        // ── Exercices supplémentaires 4ème/3ème biologie, chimie, physique ──
        if level.rawValue >= CollegeLevel.quatrieme.rawValue {
            pool += [
                ex(.sciences, .multipleChoice,
                   "Qu'est-ce qu'une liaison ionique ?",
                   ["Un transfert d'électrons entre un métal et un non-métal", "Un partage d'électrons", "Une liaison faible entre molécules", "Une liaison dans les métaux"],
                   "Un transfert d'électrons entre un métal et un non-métal",
                   "Ex : NaCl (sel). Le sodium (Na) cède un électron au chlore (Cl) → Na⁺ et Cl⁻.", "🧂", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce que l'ADN et où se trouve-t-il dans la cellule ?",
                   [], "Molécule portant l'information génétique, dans le noyau de la cellule.",
                   "L'ADN (acide désoxyribonucléique) est organisé en chromosomes dans le noyau cellulaire.", "🧬", 2),
                ex(.sciences, .multipleChoice,
                   "La formule chimique du dioxyde de carbone est :",
                   ["CO₂", "C₂O", "CO", "H₂O"], "CO₂",
                   "CO₂ = 1 carbone + 2 oxygènes. C'est le principal gaz à effet de serre produit par les combustions.", "🌿", 1),
                ex(.sciences, .trueFalse,
                   "Les ions positifs s'appellent des anions.",
                   ["Vrai", "Faux"], "Faux",
                   "Les cations sont positifs (perte d'électrons) ; les anions sont négatifs (gain d'électrons).", "⚛️", 2),
                ex(.sciences, .shortAnswer,
                   "Cite deux types d'ondes électromagnétiques.",
                   [], "Lumière visible / infrarouge / ultraviolet / rayons X / ondes radio",
                   "Le spectre électromagnétique va des ondes radio (longues) aux rayons gamma (courtes).", "🌈", 2),
                ex(.sciences, .multipleChoice,
                   "Qu'est-ce que la pression ? (symbole P)",
                   ["Une force exercée par unité de surface (Pa = N/m²)", "Une masse volumique", "Une vitesse", "Une énergie"],
                   "Une force exercée par unité de surface (Pa = N/m²)",
                   "P = F/S. L'unité est le Pascal (Pa). La pression atmosphérique ≈ 101 325 Pa.", "📊", 2),
                ex(.sciences, .multipleChoice,
                   "Dans une transformation chimique, la masse totale est :",
                   ["Conservée (loi de Lavoisier)", "Augmentée", "Diminuée", "Variable"],
                   "Conservée (loi de Lavoisier)",
                   "Lavoisier : 'Rien ne se perd, rien ne se crée, tout se transforme.' La masse totale avant = masse totale après.", "⚖️", 2),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce qu'un neurone ?",
                   [], "Cellule nerveuse qui transmet des signaux électriques dans le système nerveux.",
                   "Les neurones communiquent via des synapses. Le cerveau humain en compte environ 86 milliards.", "🧠", 2),
            ]
        }

        // ── Lycée : ADN/génétique, Newton, thermo, chimie organique, optique ──
        if level.isLycee {
            pool += [
                ex(.sciences, .multipleChoice,
                   "Qu'est-ce que l'ADN ?",
                   ["Le support de l'information génétique", "Une protéine", "Une cellule", "Un organe"],
                   "Le support de l'information génétique",
                   "L'ADN (acide désoxyribonucléique) contient toute l'information génétique d'un organisme.", "🧬", 3),
                ex(.sciences, .multipleChoice,
                   "La méiose produit :",
                   ["Des cellules reproductrices (gamètes)", "Des cellules somatiques", "Des anticorps", "Des neurones"],
                   "Des cellules reproductrices (gamètes)",
                   "La méiose produit des gamètes (ovule et spermatozoïde) avec la moitié du nombre de chromosomes.", "🧫", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce que le pH d'une solution ?",
                   [], "Mesure de l'acidité/basicité, de 0 (acide fort) à 14 (base forte), 7 = neutre.",
                   "Le pH mesure la concentration en ions H⁺. pH < 7 = acide, pH = 7 = neutre, pH > 7 = basique.", "🧪", 3),
                ex(.sciences, .multipleChoice,
                   "La première loi de Newton (principe d'inertie) stipule que :",
                   ["Un objet sans force nette reste à vitesse constante", "F = ma", "Action = réaction", "L'énergie est conservée"],
                   "Un objet sans force nette reste à vitesse constante",
                   "Si ΣF = 0, v = constante (objet au repos ou en MRU). C'est le principe d'inertie.", "⚖️", 3),
                ex(.sciences, .shortAnswer,
                   "Énonce la troisième loi de Newton.",
                   [], "Si A exerce une force sur B, alors B exerce une force égale et opposée sur A.",
                   "C'est le principe des actions réciproques : les forces s'exercent toujours par paires.", "⚖️", 3),
                ex(.sciences, .multipleChoice,
                   "La thermodynamique s'intéresse à :",
                   ["Les échanges d'énergie thermique", "La composition des atomes", "La génétique", "L'optique"],
                   "Les échanges d'énergie thermique",
                   "La thermodynamique étudie la chaleur, le travail et les transformations d'énergie.", "🌡️", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce qu'un alcane ? Donne un exemple.",
                   [], "Hydrocarbure saturé de formule CₙH₂ₙ₊₂. Ex : méthane CH₄, éthane C₂H₆.",
                   "Les alcanes sont les hydrocarbures les plus simples, sans double liaison C=C.", "🧪", 3),
                ex(.sciences, .multipleChoice,
                   "L'évolution des espèces selon Darwin est due à :",
                   ["La sélection naturelle", "La volonté des individus", "Le hasard seul", "La génétique uniquement"],
                   "La sélection naturelle",
                   "Les individus les mieux adaptés survivent et se reproduisent davantage, transmettant leurs caractères.", "🐦", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce qu'une mutation génétique ?",
                   [], "Une modification permanente de la séquence d'ADN.",
                   "Les mutations peuvent être neutres, bénéfiques ou délétères. Elles sont la source de la variabilité génétique.", "🧬", 3),
                ex(.sciences, .multipleChoice,
                   "La loi de réfraction (Snell-Descartes) relie :",
                   ["L'angle d'incidence et l'angle de réfraction selon les indices optiques", "La vitesse et la masse", "La charge et le champ", "La pression et le volume"],
                   "L'angle d'incidence et l'angle de réfraction selon les indices optiques",
                   "n₁ sin(θ₁) = n₂ sin(θ₂). La lumière change de direction en changeant de milieu.", "🔦", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce que l'effet de serre ?",
                   [], "Les gaz atmosphériques (CO₂, CH₄) retiennent la chaleur terrestre, réchauffant la Terre.",
                   "L'effet de serre naturel est indispensable. Son amplification par l'homme provoque le réchauffement climatique.", "🌍", 2),
                ex(.sciences, .multipleChoice,
                   "La liaison peptidique relie dans une protéine :",
                   ["Deux acides aminés", "Deux nucléotides", "Deux glucoses", "Deux lipides"],
                   "Deux acides aminés",
                   "Les protéines sont des chaînes d'acides aminés reliés par des liaisons peptidiques.", "🧬", 3),
                ex(.sciences, .shortAnswer,
                   "Donne la formule de l'énergie cinétique.",
                   [], "Ec = ½ × m × v²",
                   "L'énergie cinétique (en joules) dépend de la masse (kg) et du carré de la vitesse (m/s).", "⚡", 3),
                ex(.sciences, .multipleChoice,
                   "Le développement durable cherche à :",
                   ["Satisfaire les besoins présents sans compromettre ceux des générations futures", "Maximiser la croissance économique", "Préserver uniquement la nature", "Arrêter tout développement"],
                   "Satisfaire les besoins présents sans compromettre ceux des générations futures",
                   "Définition du rapport Brundtland (1987) : trois piliers — économique, social, environnemental.", "🌱", 2),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce qu'un anticorps ?",
                   [], "Protéine produite par le système immunitaire pour neutraliser un antigène.",
                   "Les anticorps (immunoglobulines) reconnaissent et se lient aux antigènes (virus, bactéries).", "🛡️", 3),
                ex(.sciences, .multipleChoice,
                   "Le potentiel d'action d'un neurone correspond à :",
                   ["Une variation rapide du potentiel électrique de la membrane neuronale", "Une hormone cérébrale", "Un réflexe musculaire", "La structure de l'ADN"],
                   "Une variation rapide du potentiel électrique de la membrane neuronale",
                   "Le potentiel d'action ('signal nerveux') se propage le long de l'axone à grande vitesse.", "⚡", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce que l'énergie potentielle ?",
                   [], "Énergie stockée en raison de la position ou de la configuration d'un objet. Ep = mgh.",
                   "Ex : Une balle en hauteur a de l'énergie potentielle gravitationnelle. Ep = masse × g × hauteur.", "⬆️", 3),
                ex(.sciences, .multipleChoice,
                   "La photosynthèse a lieu principalement dans quel organe de la plante ?",
                   ["La feuille (dans les chloroplastes)", "La racine", "La tige", "La fleur"],
                   "La feuille (dans les chloroplastes)",
                   "Les feuilles sont riches en chloroplastes qui contiennent de la chlorophylle — pigment vert capturant la lumière.", "🍃", 2),
                ex(.sciences, .multipleChoice,
                   "Qu'est-ce que la tension superficielle ?",
                   ["La force qui maintient la surface d'un liquide comme une 'peau'", "La pression sous-marine", "La force de gravité", "Une propriété des gaz"],
                   "La force qui maintient la surface d'un liquide comme une 'peau'",
                   "La tension superficielle permet aux insectes de marcher sur l'eau. Elle est due aux liaisons hydrogène.", "💧", 3),
                ex(.sciences, .shortAnswer,
                   "Qu'est-ce qu'un isotope ?",
                   [], "Atome du même élément avec le même nombre de protons mais un nombre différent de neutrons.",
                   "Ex : Carbone 12 (⁶C) et Carbone 14 (⁶C) — même nombre de protons (6) mais différents neutrons.", "⚛️", 3),
                ex(.sciences, .trueFalse,
                   "La fission nucléaire libère de l'énergie.",
                   ["Vrai", "Faux"], "Vrai",
                   "La fission scinde un noyau lourd (ex : uranium-235) en noyaux plus légers + énergie. C'est le principe du réacteur nucléaire.", "☢️", 3),
            ]
        }

        // Exercices de base supplémentaires (tous niveaux)
        pool += [
            ex(.sciences, .multipleChoice,
               "Qu'est-ce que la gravité ?",
               ["La force d'attraction entre deux masses", "Une forme d'énergie", "Un type de lumière", "Une réaction chimique"],
               "La force d'attraction entre deux masses",
               "Newton a formulé la loi de gravitation universelle : F = G × m₁ × m₂ / r².", "🍎", 1),
            ex(.sciences, .shortAnswer,
               "Cite deux exemples d'êtres vivants unicellulaires.",
               [], "Bactérie / amibe / paramécie / levure / algue unicellulaire",
               "Les êtres unicellulaires sont constitués d'une seule cellule. Les bactéries n'ont pas de noyau (procaryotes).", "🔬", 1),
            ex(.sciences, .multipleChoice,
               "L'électricité statique se produit quand :",
               ["Des charges électriques s'accumulent sur un objet", "Un courant électrique circule", "Un aimant attire un objet", "On chauffe un métal"],
               "Des charges électriques s'accumulent sur un objet",
               "Frotter un ballon crée de l'électricité statique. Les charges opposées s'attirent, les charges identiques se repoussent.", "⚡", 2),
            ex(.sciences, .shortAnswer,
               "Quel est le rôle du foie dans la digestion ?",
               [], "Produit la bile pour émulsionner les graisses et détoxifie le sang.",
               "Le foie est la plus grande glande de l'organisme. Il joue aussi un rôle dans le métabolisme des glucides.", "🫀", 2),
            ex(.sciences, .trueFalse,
               "La chaleur se transmet du froid vers le chaud.",
               ["Vrai", "Faux"], "Faux",
               "La chaleur se transfère toujours du corps le plus chaud vers le plus froid, jusqu'à l'équilibre thermique.", "🌡️", 1),
        ]

        return pool
    }

    // MARK: - Communication sociale TSA (70+ exercices)
    private static func communicationExercises(level: CollegeLevel) -> [CollegeExercise] {
        var pool: [CollegeExercise] = []

        // ── Reconnaître les émotions ──
        pool += [
            ex(.communication, .multipleChoice,
               "Ton camarade a les sourcils froncés et les bras croisés. Il ressent probablement :",
               ["De la colère ou de la frustration", "De la joie", "De la surprise", "De la peur"],
               "De la colère ou de la frustration",
               "Les sourcils froncés + bras croisés sont souvent des signaux non-verbaux de mécontentement.", "😠", 1),
            ex(.communication, .multipleChoice,
               "Quelqu'un rit, a les yeux plissés et les joues rosées. Il ressent :",
               ["De la joie", "De la peur", "De la tristesse", "Du dégoût"],
               "De la joie",
               "Le sourire sincère (dit sourire de Duchenne) atteint aussi les yeux — les coins se plissent.", "😊", 1),
            ex(.communication, .multipleChoice,
               "Une personne regarde par terre, parle doucement et évite le contact visuel. Elle ressent plutôt :",
               ["De la tristesse ou de la honte", "De la colère", "De l'excitation", "Du mépris"],
               "De la tristesse ou de la honte",
               "Le regard fuyant et la posture basse sont souvent associés à la tristesse ou à un sentiment de honte.", "😔", 2),
            ex(.communication, .trueFalse,
               "Les émotions s'expriment uniquement avec des mots.",
               ["Vrai", "Faux"], "Faux",
               "Les émotions s'expriment aussi par les expressions du visage, le ton de la voix et les gestes.", "🎭", 1),
            ex(.communication, .multipleChoice,
               "Quand quelqu'un dit 'ça va' mais pleure, à quel signal dois-tu faire confiance ?",
               ["Au comportement (les larmes)", "Aux mots ('ça va')", "Aux deux de façon égale", "À aucun des deux"],
               "Au comportement (les larmes)",
               "Quand les mots et le langage corporel sont contradictoires, le comportement non-verbal est souvent plus révélateur.", "👀", 2),
            ex(.communication, .multipleChoice,
               "Ton professeur soupire en regardant le fond de la classe et lève les yeux au ciel. Il exprime probablement :",
               ["De l'impatience ou de la frustration", "De la joie", "De la surprise", "De l'admiration"],
               "De l'impatience ou de la frustration",
               "Soupirer et lever les yeux au ciel sont des signaux non-verbaux d'impatience ou d'exaspération.", "😤", 2),
            ex(.communication, .oral,
               "Décris en une phrase ce que ressent quelqu'un qui a les mains moites et le cœur qui bat vite avant un exposé.",
               [], "Il ressent de l'anxiété ou du stress.",
               "Ces symptômes physiques sont des réponses du corps au stress. C'est une réaction normale.", "😰", 1),
            ex(.communication, .multipleChoice,
               "La peur se reconnaît souvent à :",
               ["Les yeux écarquillés et la bouche ouverte", "Le sourire large", "Les sourcils levés et le nez plissé", "Un regard fixe et calme"],
               "Les yeux écarquillés et la bouche ouverte",
               "La peur dilate les yeux pour mieux voir la menace. C'est une réaction biologique automatique.", "😱", 2),

            // ── Exprimer ses besoins ──
            ex(.communication, .oral,
               "Demande poliment à quelqu'un de répéter ce qu'il vient de dire.",
               [], "« Excuse-moi, peux-tu répéter s'il te plaît ? »",
               "Demander de répéter est naturel et poli. C'est une compétence sociale importante.", "👂", 1),
            ex(.communication, .oral,
               "Comment exprimer que tu es fatigué(e) à un adulte ?",
               [], "« Je me sens fatigué(e), j'ai besoin d'une pause. »",
               "Exprimer ses besoins clairement aide les autres à nous soutenir.", "😴", 2),
            ex(.communication, .multipleChoice,
               "Si tu as trop chaud en classe, que peux-tu dire au professeur ?",
               ["« Monsieur/Madame, j'ai chaud, peut-on ouvrir la fenêtre ? »", "Rien, c'est impoli", "Partir de la classe", "Crier"],
               "« Monsieur/Madame, j'ai chaud, peut-on ouvrir la fenêtre ? »",
               "Exprimer un besoin physique est légitime. Formuler une demande polie avec une raison est la bonne façon.", "🌡️", 1),
            ex(.communication, .oral,
               "Tu te sens submergé(e) par le bruit de la cantine. Comment le dire à un adulte ?",
               [], "« J'ai besoin d'un endroit plus calme, le bruit me fatigue beaucoup. »",
               "Il est important de nommer ce qu'on ressent et d'exprimer clairement son besoin. Les adultes peuvent t'aider.", "🔊", 2),
            ex(.communication, .multipleChoice,
               "Si tu ne comprends pas une consigne en classe, tu dois :",
               ["Lever la main et demander", "Ne rien faire", "Faire autre chose", "Partir"],
               "Lever la main et demander",
               "Lever la main pour demander de l'aide est la bonne stratégie en classe.", "✋", 1),
            ex(.communication, .oral,
               "Tu as besoin d'aide pour un exercice. Que dis-tu à ton camarade ?",
               [], "« Peux-tu m'expliquer cette partie, s'il te plaît ? »",
               "Demander de l'aide est une force, pas une faiblesse. Une demande polie est toujours bien accueillie.", "🤝", 1),

            // ── Règles de conversation ──
            ex(.communication, .trueFalse,
               "Couper la parole à quelqu'un pendant qu'il parle est poli.",
               ["Vrai", "Faux"], "Faux",
               "Il faut attendre que l'autre ait fini de parler avant de prendre la parole.", "🚦", 1),
            ex(.communication, .multipleChoice,
               "Quand on veut parler à quelqu'un, on commence par :",
               ["Appeler son prénom / dire bonjour", "Parler directement du sujet", "Attendre qu'il finisse", "Lever la main"],
               "Appeler son prénom / dire bonjour",
               "Attirer l'attention poliment avant de parler montre du respect.", "👋", 1),
            ex(.communication, .multipleChoice,
               "Pendant une conversation, il est important de :",
               ["Laisser l'autre parler et attendre son tour", "Parler le plus possible", "Rester silencieux tout le temps", "Changer de sujet souvent"],
               "Laisser l'autre parler et attendre son tour",
               "La conversation est un échange : chacun parle à tour de rôle. Écouter est aussi important que parler.", "🗣️", 1),
            ex(.communication, .oral,
               "Comment indiques-tu à quelqu'un que tu l'écoutes, sans couper la parole ?",
               [], "Hocher la tête, dire 'oui', 'je vois', maintenir un contact visuel bref.",
               "Ces signaux montrent que tu es attentif(ve) sans interrompre. Ils encouragent l'autre à continuer.", "👂", 2),
            ex(.communication, .multipleChoice,
               "Combien de temps peut-on parler d'un seul sujet à quelqu'un qui ne partage pas ce centre d'intérêt ?",
               ["Quelques minutes maximum puis demander l'avis de l'autre", "Sans limite si c'est intéressant", "30 minutes", "Toute la conversation"],
               "Quelques minutes maximum puis demander l'avis de l'autre",
               "Équilibrer les sujets montre de l'intérêt pour l'autre. On peut demander : 'Et toi, qu'est-ce que tu aimes ?'", "⏱️", 2),
            ex(.communication, .trueFalse,
               "Pour changer de sujet dans une conversation, on peut dire : 'Au fait, j'ai pensé à quelque chose...'",
               ["Vrai", "Faux"], "Vrai",
               "Des formules de transition comme 'au fait', 'à propos', 'ça me fait penser à...' permettent de changer de sujet poliment.", "💬", 2),

            // ── Gestion des conflits ──
            ex(.communication, .oral,
               "Comment résoudre un désaccord avec un camarade ?",
               [], "En parlant calmement et en écoutant son point de vue.",
               "La résolution de conflit passe par le dialogue calme et l'écoute mutuelle.", "🤝", 2),
            ex(.communication, .multipleChoice,
               "Un camarade t'a pris ton stylo sans demander. Que fais-tu ?",
               ["Tu lui dis calmement : 'C'est mon stylo, peux-tu me le rendre ?'", "Tu lui cries dessus", "Tu le laisses faire", "Tu te plains à tout le monde"],
               "Tu lui dis calmement : 'C'est mon stylo, peux-tu me le rendre ?'",
               "Exprimer le problème directement et calmement est la meilleure approche. Évite l'escalade.", "✏️", 1),
            ex(.communication, .multipleChoice,
               "Si une dispute éclate et que tu te sens très en colère, la meilleure chose à faire est :",
               ["Se retirer et se calmer avant de parler", "Dire tout ce qu'on pense immédiatement", "Partir sans rien dire pour toujours", "Faire semblant que ça n'a pas d'importance"],
               "Se retirer et se calmer avant de parler",
               "Prendre du recul permet de réduire l'intensité émotionnelle et d'éviter de dire des choses qu'on regrette.", "😤", 2),
            ex(.communication, .oral,
               "Comment dire à un(e) ami(e) que quelque chose qu'il/elle a fait t'a blessé(e) ?",
               [], "« Quand tu as dit/fait ça, je me suis senti(e)... J'aurais préféré que... »",
               "La formule en 'je' (message 'je') exprime le ressenti sans accuser l'autre, ce qui favorise l'écoute.", "💬", 3),
            ex(.communication, .multipleChoice,
               "Comment refuser poliment de faire quelque chose ?",
               ["« Non merci, ce n'est pas pour moi. »", "« Jamais ! »", "Ignorer la demande", "Fuir"],
               "« Non merci, ce n'est pas pour moi. »",
               "On peut refuser poliment sans se justifier longuement. 'Non merci' est une phrase complète.", "🙅", 2),

            // ── Sarcasme et second degré ──
            ex(.communication, .multipleChoice,
               "Le sarcasme, c'est :",
               ["Dire le contraire de ce qu'on pense de façon moqueuse", "Un compliment sincère", "Une question directe", "Une règle de politesse"],
               "Dire le contraire de ce qu'on pense de façon moqueuse",
               "Le sarcasme est souvent difficile à détecter pour les personnes avec TSA — c'est normal.", "💬", 3),
            ex(.communication, .multipleChoice,
               "Un camarade regarde la pluie par la fenêtre et dit avec un soupir : 'Super temps pour un pique-nique !' Il veut dire :",
               ["Le temps est horrible pour un pique-nique (ironie)", "Il veut vraiment faire un pique-nique", "Il est content", "Il ne sait pas quel temps il fait"],
               "Le temps est horrible pour un pique-nique (ironie)",
               "L'ironie consiste à dire le contraire de ce qu'on pense. Le ton de voix et le contexte aident à la détecter.", "🌧️", 3),
            ex(.communication, .trueFalse,
               "Si tu n'es pas sûr(e) qu'une remarque est sérieuse ou ironique, tu peux demander : 'Tu plaisantes ?'",
               ["Vrai", "Faux"], "Vrai",
               "Demander une clarification est tout à fait acceptable. Mieux vaut poser la question que de mal comprendre.", "❓", 2),
            ex(.communication, .oral,
               "Ton camarade dit : 'Évidemment, tu as encore raison !' avec un ton moqueur. Comment sais-tu qu'il est sarcastique ?",
               [], "Au ton moqueur, au contexte et à l'expression du visage (sourire ironique).",
               "Pour détecter le sarcasme, combine le ton de voix, le contexte et les expressions faciales.", "😏", 3),

            // ── Situations scolaires ──
            ex(.communication, .oral,
               "Comment demandes-tu à ton professeur d'expliquer à nouveau une notion que tu n'as pas comprise ?",
               [], "« Monsieur/Madame, je n'ai pas bien compris cette partie. Pouvez-vous l'expliquer autrement ? »",
               "Demander une explication différente est une excellente stratégie d'apprentissage. Le professeur appréciera ton engagement.", "🏫", 1),
            ex(.communication, .multipleChoice,
               "En travail de groupe, ton camarade ne fait rien. Que fais-tu ?",
               ["Tu lui demandes calmement ce qu'il peut faire", "Tu fais tout tout seul en silence", "Tu te plains au prof immédiatement", "Tu arrêtes de travailler aussi"],
               "Tu lui demandes calmement ce qu'il peut faire",
               "Commencer par une conversation directe est plus efficace. Si ça ne marche pas, tu peux ensuite en parler à l'enseignant.", "👥", 2),
            ex(.communication, .multipleChoice,
               "Tu passes un exposé oral et tu oublies ce que tu allais dire. Que fais-tu ?",
               ["Tu prends une pause et regardes tes notes", "Tu cours hors de la classe", "Tu inventes n'importe quoi", "Tu ne dis plus rien"],
               "Tu prends une pause et regardes tes notes",
               "Il est normal d'avoir un blanc. Prendre 5 secondes pour consulter ses notes est acceptable et professionnel.", "🗣️", 2),
            ex(.communication, .oral,
               "Un camarade veut copier ton devoir. Comment refuses-tu sans vexer ?",
               [], "« Je préfère ne pas, mais je peux t'expliquer comment j'ai fait. »",
               "Tu peux refuser tout en proposant une aide alternative. C'est honnête envers lui et envers toi.", "📝", 2),

            // ── Situations sociales ──
            ex(.communication, .multipleChoice,
               "Comment rejoindre un groupe de camarades qui parlent entre eux ?",
               ["Approcher, attendre une pause puis dire 'Bonjour, je peux me joindre à vous ?'", "S'asseoir sans rien dire", "Interrompre immédiatement", "Ne jamais approcher"],
               "Approcher, attendre une pause puis dire 'Bonjour, je peux me joindre à vous ?'",
               "Attendre une pause naturelle et demander la permission montre du respect pour la conversation en cours.", "👥", 2),
            ex(.communication, .oral,
               "Un camarade t'invite à sa fête d'anniversaire mais tu ne veux pas y aller. Comment refuses-tu gentiment ?",
               [], "« Merci de m'inviter ! Je ne pourrai pas venir, mais joyeux anniversaire ! »",
               "On peut refuser une invitation sans donner d'explication détaillée. La reconnaissance + le refus poli suffit.", "🎂", 2),
            ex(.communication, .multipleChoice,
               "Tu veux te faire un nouvel ami. Quel est un bon premier pas ?",
               ["Trouver un intérêt commun et en parler", "Lui dire tous tes secrets le premier jour", "L'observer sans lui parler", "Lui offrir des cadeaux"],
               "Trouver un intérêt commun et en parler",
               "Les amitiés se construisent souvent autour d'intérêts partagés. Commencer par une question sur ses centres d'intérêt est efficace.", "🤝", 1),
            ex(.communication, .trueFalse,
               "Il est normal de ne pas vouloir parler à tout le monde tout le temps.",
               ["Vrai", "Faux"], "Vrai",
               "Chacun a ses besoins sociaux. Avoir besoin de solitude ou de calme est tout à fait normal.", "🧘", 1),

            // ── Stress et régulation émotionnelle ──
            ex(.communication, .multipleChoice,
               "Quand tu te sens très stressé(e), quelle technique peut t'aider à te calmer ?",
               ["Respiration lente : inspirer 4s, retenir 4s, expirer 4s", "Regarder des écrans", "Courir partout", "Parler très vite"],
               "Respiration lente : inspirer 4s, retenir 4s, expirer 4s",
               "La respiration contrôlée active le système nerveux parasympathique et réduit le stress rapidement.", "🧘", 2),
            ex(.communication, .oral,
               "Tu sens que tu vas pleurer en classe parce que tu es frustré(e). Que peux-tu faire ?",
               [], "Demander à sortir un moment, respirer calmement, puis revenir quand tu te sens mieux.",
               "Reconnaître ses émotions et s'accorder une pause est une excellente stratégie de régulation émotionnelle.", "😢", 2),
            ex(.communication, .multipleChoice,
               "La frustration apparaît souvent quand :",
               ["Quelque chose bloque nos objectifs ou nos attentes", "On est très content", "On a fini son travail", "On reçoit un compliment"],
               "Quelque chose bloque nos objectifs ou nos attentes",
               "La frustration naît de l'obstacle. La reconnaître permet de mieux la gérer au lieu de la laisser exploser.", "😤", 2),
            ex(.communication, .multipleChoice,
               "Que signifie 'réguler ses émotions' ?",
               ["Les gérer de façon à pouvoir agir de manière adaptée", "Ne jamais les ressentir", "Les cacher toujours", "Les exprimer à pleine voix"],
               "Les gérer de façon à pouvoir agir de manière adaptée",
               "Réguler ses émotions ne veut pas dire les supprimer. C'est les reconnaître et choisir comment y répondre.", "🧠", 3),
            ex(.communication, .oral,
               "Nomme trois choses que tu peux faire quand tu te sens submergé(e) par les émotions.",
               [], "Respirer lentement / se retirer dans un endroit calme / parler à quelqu'un de confiance.",
               "Avoir un plan pour les moments difficiles aide à traverser les crises plus facilement.", "🛠️", 3),
            ex(.communication, .trueFalse,
               "Ressentir de la colère, c'est toujours mauvais.",
               ["Vrai", "Faux"], "Faux",
               "La colère est une émotion normale qui signale une injustice ou une frustration. C'est la façon de l'exprimer qui compte.", "😡", 2),
            ex(.communication, .multipleChoice,
               "Après une dispute, la meilleure façon de récupérer la relation est :",
               ["Reconnaître sa part de responsabilité et s'excuser si nécessaire", "Faire comme si rien ne s'était passé", "Attendre que l'autre s'excuse en premier", "Éviter la personne"],
               "Reconnaître sa part de responsabilité et s'excuser si nécessaire",
               "Les excuses sincères et les explications aident à reconstruire la confiance après un conflit.", "🤝", 3),

            // ── Niveau intermédiaire/avancé ──
            ex(.communication, .oral,
               "Quelqu'un te fait un compliment. Comment répondre naturellement ?",
               [], "« Merci, c'est gentil ! » ou « Merci beaucoup. »",
               "Accepter un compliment simplement avec un merci est la réponse la plus naturelle.", "😊", 1),
            ex(.communication, .multipleChoice,
               "Si un adulte te parle de façon condescendante (comme si tu étais petit enfant), tu peux :",
               ["Exprimer poliment que tu préfères être traité(e) différemment", "Crier", "Quitter la pièce", "Tout accepter en silence"],
               "Exprimer poliment que tu préfères être traité(e) différemment",
               "On peut défendre ses besoins avec calme. Ex : 'Je comprends mieux quand on m'explique directement.'", "🗣️", 3),
            ex(.communication, .trueFalse,
               "Le silence dans une conversation est toujours gênant et doit être évité.",
               ["Vrai", "Faux"], "Faux",
               "Les silences font partie de la conversation. Ils permettent de réfléchir et ne sont pas toujours gênants.", "🤫", 2),
            ex(.communication, .multipleChoice,
               "Ton professeur te rend une mauvaise note sur un travail que tu avais soigné. La meilleure réaction est :",
               ["Lui demander calmement ce que tu peux améliorer", "Jeter le devoir", "Ne plus jamais faire d'efforts", "Crier"],
               "Lui demander calmement ce que tu peux améliorer",
               "Demander un retour constructif montre de la maturité et aide à progresser.", "📝", 2),
            ex(.communication, .oral,
               "Comment te présentes-tu à quelqu'un que tu ne connais pas ?",
               [], "« Bonjour, je m'appelle [prénom]. Et toi ? »",
               "Une présentation simple avec prénom et une question de retour montre de l'intérêt pour l'autre.", "👋", 1),
            ex(.communication, .multipleChoice,
               "Quand quelqu'un te parle, regarder son visage (sans fixer) sert à :",
               ["Montrer qu'on écoute et capter les émotions", "Intimider", "Analyser son apparence", "Rien de spécial"],
               "Montrer qu'on écoute et capter les émotions",
               "Le contact visuel (modéré) est un signal d'écoute active. Il aide aussi à comprendre les émotions de l'interlocuteur.", "👀", 2),
            ex(.communication, .trueFalse,
               "Quand quelqu'un dit 'ça va' mais a l'air triste, il ressent probablement de la tristesse.",
               ["Vrai", "Faux"], "Vrai",
               "Les expressions et le ton de voix peuvent indiquer une émotion différente des mots.", "😟", 2),

            // ── Numériquement et réseaux sociaux ──
            ex(.communication, .multipleChoice,
               "Avant d'envoyer un message en ligne, il faut surtout vérifier :",
               ["Qu'il ne blesse pas les sentiments de l'autre et qu'on ne le regrettera pas", "Qu'il est suffisamment long", "Qu'il contient des emojis", "Qu'il est envoyé rapidement"],
               "Qu'il ne blesse pas les sentiments de l'autre et qu'on ne le regrettera pas",
               "Les messages écrits peuvent être mal interprétés sans le ton de voix. Relire avant d'envoyer est très utile.", "📱", 2),
            ex(.communication, .trueFalse,
               "Ce qu'on écrit en ligne reste souvent visible très longtemps.",
               ["Vrai", "Faux"], "Vrai",
               "Les captures d'écran et les historiques peuvent garder les messages indéfiniment. Prudence en ligne.", "🌐", 2),
            ex(.communication, .oral,
               "Quelqu'un t'envoie un message blessant en ligne. Que fais-tu ?",
               [], "Ne pas répondre sous le coup de l'émotion. En parler à un adulte de confiance. Signaler si nécessaire.",
               "La règle d'or : ne jamais répondre en colère en ligne. Prendre du recul et en parler à un adulte.", "🛡️", 2),
            ex(.communication, .multipleChoice,
               "Si tu veux savoir si un camarade est disponible pour parler, tu peux :",
               ["Lui demander 'Est-ce que tu as une minute ?' avant de commencer", "Commencer à parler immédiatement", "Lui écrire sans attendre de réponse", "Ne jamais l'approcher"],
               "Lui demander 'Est-ce que tu as une minute ?' avant de commencer",
               "Vérifier la disponibilité de l'autre montre du respect. C'est une compétence sociale importante.", "⏰", 1),

            // ── Empathie et perspective sociale ──
            ex(.communication, .multipleChoice,
               "L'empathie, c'est :",
               ["La capacité à comprendre et ressentir ce que l'autre vit", "Être d'accord avec tout le monde", "Imiter les autres", "Éviter les conflits"],
               "La capacité à comprendre et ressentir ce que l'autre vit",
               "L'empathie permet de se mettre à la place de l'autre. Elle est différente de la sympathie (partager la même émotion).", "❤️", 2),
            ex(.communication, .oral,
               "Ton ami est triste parce qu'il a raté un examen. Que lui dis-tu ?",
               [], "« Je suis désolé(e). C'est difficile. Tu veux qu'on en parle ? »",
               "Reconnaître l'émotion de l'autre et offrir son écoute — sans minimiser ('c'est pas grave') — est la réponse empathique.", "🤗", 2),
            ex(.communication, .trueFalse,
               "Tout le monde voit et ressent les situations de la même façon.",
               ["Vrai", "Faux"], "Faux",
               "Les gens ont des perspectives différentes selon leur vécu, leur culture et leur personnalité. C'est normal.", "👁️", 1),
            ex(.communication, .multipleChoice,
               "Quand quelqu'un te parle de quelque chose qui t'ennuie, tu devrais :",
               ["Écouter poliment et montrer de l'intérêt", "Changer de sujet immédiatement", "Regarder ailleurs", "Quitter la conversation"],
               "Écouter poliment et montrer de l'intérêt",
               "Écouter les centres d'intérêt des autres (même si ce n'est pas le tien) est une marque de respect social.", "👂", 2),

            // ── Gestion des transitions et des changements ──
            ex(.communication, .oral,
               "Tu dois changer d'emploi du temps sans prévenance. Comment gères-tu cette situation ?",
               [], "Prendre une grande inspiration, accepter que le changement soit difficile, demander des explications si besoin.",
               "Les changements imprévus peuvent être difficiles. Des stratégies comme la respiration et demander des infos aident.", "📅", 2),
            ex(.communication, .multipleChoice,
               "Quand tu te retrouves dans une situation imprévue, une bonne stratégie est :",
               ["Identifier ce que tu contrôles et te concentrer dessus", "Paniquer immédiatement", "Ignorer la situation", "Tout quitter"],
               "Identifier ce que tu contrôles et te concentrer dessus",
               "Se concentrer sur ce qu'on peut contrôler réduit l'anxiété face à l'imprévu.", "🧠", 3),

            // ── Reconnaissance des indices sociaux ──
            ex(.communication, .multipleChoice,
               "Quand une conversation est terminée, les gens signalent souvent cela par :",
               ["Un résumé ('Bon, bref...'), regarder sa montre, se lever ou commencer à s'éloigner", "Un silence de 1 seconde", "En continuant à parler", "En changeant de sujet"],
               "Un résumé ('Bon, bref...'), regarder sa montre, se lever ou commencer à s'éloigner",
               "Ces indices non-verbaux et verbaux signalent que la personne souhaite terminer la conversation.", "🚪", 2),
            ex(.communication, .oral,
               "Comment sais-tu que quelqu'un veut que tu arrêtes de parler d'un sujet ?",
               [], "Il regarde ailleurs, répond brièvement, bâille, ou dit des formules comme 'ah oui, intéressant...' sans poser de questions.",
               "Ces signaux subtils indiquent un désintérêt. Remarquer et s'adapter montre une bonne conscience sociale.", "👀", 3),
            ex(.communication, .multipleChoice,
               "Dire 'merci' après qu'on t'a aidé est important parce que :",
               ["Cela montre de la gratitude et encourage l'autre à aider à nouveau", "C'est une obligation légale", "Ça n'a pas d'importance", "Cela montre de la faiblesse"],
               "Cela montre de la gratitude et encourage l'autre à aider à nouveau",
               "Exprimer sa gratitude renforce les relations sociales et le respect mutuel.", "🙏", 1),

            // ── Habiletés conversationnelles avancées ──
            ex(.communication, .trueFalse,
               "Dans une conversation, poser des questions sur l'autre est un bon moyen de montrer de l'intérêt.",
               ["Vrai", "Faux"], "Vrai",
               "Les questions montrent qu'on s'intéresse à l'autre et permettent à la conversation de progresser naturellement.", "💬", 1),
            ex(.communication, .multipleChoice,
               "Quelle formule utiliser pour donner son avis sans blesser ?",
               ["'Je pense que...' ou 'À mon avis...'", "'Tu as tort parce que...'", "'C'est nul !'", "'Tout le monde sait que...'"],
               "'Je pense que...' ou 'À mon avis...'",
               "Commencer par 'je' plutôt que 'tu' permet d'exprimer son point de vue sans accuser l'autre.", "💬", 2),
            ex(.communication, .oral,
               "Tu n'es pas d'accord avec ton professeur sur quelque chose. Comment exprimes-tu ton désaccord respectueusement ?",
               [], "« Monsieur/Madame, je comprends votre point, mais j'ai une question — pourquoi...? »",
               "Exprimer un désaccord en questionnant plutôt qu'en affirmant est plus respectueux et plus efficace.", "🏫", 3),
        ]

        return pool
    }

    // MARK: - Helper
    private static func ex(_ subject: CollegeSubject, _ mode: CollegeExerciseMode,
                            _ question: String, _ choices: [String], _ answer: String,
                            _ explanation: String, _ emoji: String, _ difficulty: Int) -> CollegeExercise {
        CollegeExercise(subject: subject, mode: mode, question: question, choices: choices,
                        correctAnswer: answer, explanation: explanation, emoji: emoji, difficulty: difficulty)
    }
}
